export const THEME = {
  gold: "#FFD700",
  background: "#1A1A1B",
  surface: "#2A2A2B",
  surfaceLight: "#3A3A3B",
  textPrimary: "#FAFAFA",
  textSecondary: "#A0A0A0",
  positive: "#22C55E",
  negative: "#EF4444",
  saleOpportunity: "#F59E0B",
} as const;

export const SECTOR_LABELS: Record<string, string> = {
  bank: "Banks",
  reit: "REITs",
  sin_stock: "Sin Stocks",
  cash: "Cash",
  financials: "Financials",
  telecom: "Telecom",
  industrials: "Industrials",
  utility: "Utilities",
  consumer: "Consumer",
  infrastructure: "Infrastructure",
  plantation: "Plantation",
  gaming: "Gaming",
  insurance: "Insurance",
  property: "Property",
  healthcare: "Healthcare",
  technology: "Technology",
  energy: "Energy",
  other: "Other",
};

export const SECTOR_COLORS: Record<string, string> = {
  bank: "#FFD700",
  reit: "#60A5FA",
  sin_stock: "#F59E0B",
  cash: "#A0A0A0",
  financials: "#FFD700",
  telecom: "#34D399",
  industrials: "#A78BFA",
  utility: "#06B6D4",
  consumer: "#EC4899",
  infrastructure: "#8B5CF6",
  plantation: "#84CC16",
  gaming: "#F97316",
  insurance: "#14B8A6",
  property: "#EAB308",
  healthcare: "#EF4444",
  technology: "#3B82F6",
  energy: "#F59E0B",
  other: "#6B7280",
};

export const ENTRY_SIGNAL_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  strong_buy: { label: "Strong Buy", color: "text-green-400", bg: "bg-green-500/20" },
  buy: { label: "Buy", color: "text-emerald-400", bg: "bg-emerald-500/15" },
  hold: { label: "Hold", color: "text-yellow-400", bg: "bg-yellow-500/15" },
  wait: { label: "Wait", color: "text-red-400", bg: "bg-red-500/15" },
};
